import { toast } from "sonner";

export type InvoiceLocale = "ar" | "en";

export type PrintableInvoiceStatus =
  | "DRAFT"
  | "UNPAID"
  | "PARTIALLY_PAID"
  | "PAID"
  | "OVERDUE"
  | "CANCELLED";

export type PrintableInvoice = {
  id: string;
  invoiceNumber: string;
  status: PrintableInvoiceStatus;
  issueDate: string;
  dueDate?: string | null;
  subtotal: number;
  tax: number;
  discount: number;
  total: number;
  notes?: string | null;
  client: {
    id?: string;
    name?: string | null;
    phone?: string | null;
    whatsapp?: string | null;
    whatsappNumber?: string | null;
    mobile?: string | null;
    email?: string | null;
  };
  case?: {
    id?: string;
    title?: string | null;
    caseNumber?: string | null;
  } | null;
  items: Array<{
    id?: string;
    description: string;
    quantity: number;
    unitPrice: number;
    total?: number;
  }>;
  payments?: Array<{
    id?: string;
    amount?: number;
    status?: string;
    method?: string;
    paidAt?: string | null;
    reference?: string | null;
  }>;
  tenant?: {
    id?: string;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    logoUrl?: string | null;
  } | null;
};

const COPY = {
  ar: {
    PARTIALLY_PAID: "مدفوعة جزئيًا",
    invoice: "فاتورة",
    invoiceNumber: "رقم الفاتورة",
    status: "الحالة",
    issueDate: "تاريخ الإصدار",
    dueDate: "تاريخ الاستحقاق",
    total: "الإجمالي",
    clientDetails: "بيانات الموكل",
    caseDetails: "بيانات القضية",
    noCase: "بدون قضية",
    paymentStatus: "حالة الدفعة",
    linkedPayment: "مرتبطة بدفعة",
    noLinkedPayment: "لا توجد دفعة مرتبطة",
    items: "بنود الفاتورة",
    number: "#",
    description: "الوصف",
    quantity: "الكمية",
    unitPrice: "سعر الوحدة",
    lineTotal: "الإجمالي",
    notes: "ملاحظات",
    noNotes: "لا توجد ملاحظات إضافية.",
    subtotal: "المجموع الفرعي",
    tax: "الضريبة",
    discount: "الخصم",
    finalTotal: "الإجمالي النهائي",
    officeSignature: "توقيع المكتب",
    clientSignature: "توقيع الموكل",
    generatedBy: "تم إنشاء هذه الفاتورة بواسطة Viresto",
    legalPlatform: "منصة إدارة المكاتب القانونية",
    printPopupBlocked: "يرجى السماح بفتح النوافذ المنبثقة لطباعة الفاتورة",
    whatsappGreeting: "مرحبًا",
    whatsappIntro: "نرسل لكم تفاصيل الفاتورة:",
    whatsappReview: "يرجى مراجعة الفاتورة، ولأي استفسار يمكنكم التواصل معنا.",
    regards: "مع التحية،",
    statuses: {
      DRAFT: "مسودة",
      UNPAID: "غير مدفوعة",
      PAID: "مدفوعة",
      OVERDUE: "متأخرة",
      CANCELLED: "ملغاة",
    } as Record<PrintableInvoiceStatus, string>,
    paymentStatuses: {
      PAID: "مدفوعة",
      PENDING: "معلّقة",
      OVERDUE: "متأخرة",
      CANCELLED: "ملغاة",
    } as Record<string, string>,
  },
  en: {
    PARTIALLY_PAID: "Partially paid",
    invoice: "Invoice",
    invoiceNumber: "Invoice number",
    status: "Status",
    issueDate: "Issue date",
    dueDate: "Due date",
    total: "Total",
    clientDetails: "Client details",
    caseDetails: "Case details",
    noCase: "No case",
    paymentStatus: "Payment status",
    linkedPayment: "Linked to a payment",
    noLinkedPayment: "No linked payment",
    items: "Invoice items",
    number: "#",
    description: "Description",
    quantity: "Quantity",
    unitPrice: "Unit price",
    lineTotal: "Total",
    notes: "Notes",
    noNotes: "No additional notes.",
    subtotal: "Subtotal",
    tax: "Tax",
    discount: "Discount",
    finalTotal: "Final total",
    officeSignature: "Office signature",
    clientSignature: "Client signature",
    generatedBy: "This invoice was generated by Viresto",
    legalPlatform: "Legal practice management platform",
    printPopupBlocked: "Please allow pop-ups to print the invoice",
    whatsappGreeting: "Hello",
    whatsappIntro: "Please find the invoice details below:",
    whatsappReview:
      "Please review the invoice and contact us if you have any questions.",
    regards: "Regards,",
    statuses: {
      DRAFT: "Draft",
      UNPAID: "Unpaid",
      PAID: "Paid",
      OVERDUE: "Overdue",
      CANCELLED: "Cancelled",
    } as Record<PrintableInvoiceStatus, string>,
    paymentStatuses: {
      PAID: "Paid",
      PENDING: "Pending",
      OVERDUE: "Overdue",
      CANCELLED: "Cancelled",
    } as Record<string, string>,
  },
};

function detectLocale(locale?: InvoiceLocale): InvoiceLocale {
  if (locale) return locale;

  if (typeof document !== "undefined") {
    const documentLanguage = document.documentElement.lang?.toLowerCase();
    if (documentLanguage?.startsWith("en")) return "en";
  }

  return "ar";
}

export function getInvoiceStatusLabel(
  status: PrintableInvoiceStatus,
  locale?: InvoiceLocale,
) {
  return COPY[detectLocale(locale)].statuses[status];
}

export const invoiceStatusLabels: Record<PrintableInvoiceStatus, string> =
  COPY.ar.statuses;

export function formatInvoiceNumber(invoiceNumber?: string | null) {
  if (!invoiceNumber) return "#INV";
  return invoiceNumber.startsWith("#") ? invoiceNumber : `#${invoiceNumber}`;
}

export function safeInvoiceFilename(invoiceNumber?: string | null) {
  const clean = (invoiceNumber || "invoice")
    .replace(/^#/, "")
    .replace(/[^a-zA-Z0-9\-_\u0600-\u06FF]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");

  return clean || "invoice";
}

export function normalizeWhatsAppPhone(phone?: string | null) {
  if (!phone) return "";

  const cleaned = phone.replace(/[^\d+]/g, "");

  if (cleaned.startsWith("+")) return cleaned.slice(1);
  if (cleaned.startsWith("00")) return cleaned.slice(2);
  if (cleaned.startsWith("0")) return `962${cleaned.slice(1)}`;

  return cleaned;
}

function money(value: number | null | undefined, locale: InvoiceLocale) {
  return new Intl.NumberFormat(locale === "ar" ? "ar-JO-u-nu-latn" : "en-US", {
    style: "currency",
    currency: "JOD",
    minimumFractionDigits: 3,
    maximumFractionDigits: 3,
  }).format(Number(value || 0));
}

function date(value: string | Date | null | undefined, locale: InvoiceLocale) {
  if (!value) return "-";

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return "-";

  return new Intl.DateTimeFormat(locale === "ar" ? "ar-JO-u-nu-latn" : "en-US", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(parsed);
}

function escapeHtml(value: unknown) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

const VIRESTO_BRAND_LOGO_PATH = "/viresto-logo.png";

const VIRESTO_FALLBACK_LOGO =
  "data:image/svg+xml;charset=UTF-8," +
  encodeURIComponent(`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
      <rect width="512" height="512" rx="128" fill="#ffffff"/>
      <path
        d="M116 128h82l58 166 58-166h82L294 384h-76L116 128Z"
        fill="#0f3d3e"
      />
    </svg>
  `);

function resolveLogoUrl(logoUrl?: string | null) {
  const clean = logoUrl?.trim();

  if (!clean) return VIRESTO_FALLBACK_LOGO;

  if (
    clean.startsWith("data:") ||
    clean.startsWith("blob:") ||
    /^https?:\/\//i.test(clean)
  ) {
    return clean;
  }

  if (typeof window !== "undefined") {
    try {
      return new URL(clean, window.location.origin).href;
    } catch {
      return VIRESTO_FALLBACK_LOGO;
    }
  }

  return clean;
}


function logoMarkup(
  invoice: PrintableInvoice,
  tenantName: string,
  useVirestoLockup: boolean,
) {
  const customLogoUrl = invoice.tenant?.logoUrl?.trim();

  if (useVirestoLockup) {
    const brandLogoUrl =
      typeof window !== "undefined"
        ? new URL(VIRESTO_BRAND_LOGO_PATH, window.location.origin).href
        : VIRESTO_BRAND_LOGO_PATH;

    return `
      <div class="brand-logo brand-logo-lockup">
        <img
          src="${escapeHtml(brandLogoUrl)}"
          alt="Viresto"
          onerror="this.onerror=null;this.src='${VIRESTO_FALLBACK_LOGO}';"
        />
      </div>
    `;
  }

  if (customLogoUrl) {
    const logoUrl = resolveLogoUrl(customLogoUrl);

    return `
      <div class="brand-logo">
        <img
          src="${escapeHtml(logoUrl)}"
          alt="${escapeHtml(tenantName)}"
          onerror="this.onerror=null;this.style.display='none';this.nextElementSibling.style.display='flex';"
        />
        <span class="brand-logo-fallback" style="display:none;">
          ${escapeHtml(tenantName.slice(0, 1).toUpperCase())}
        </span>
      </div>
    `;
  }

  return `
    <div class="brand-logo">
      <span class="brand-logo-fallback">
        ${escapeHtml(tenantName.slice(0, 1).toUpperCase())}
      </span>
    </div>
  `;
}

export function buildInvoiceWhatsAppMessage(
  invoice: PrintableInvoice,
  requestedLocale?: InvoiceLocale,
) {
  const locale = detectLocale(requestedLocale);
  const copy = COPY[locale];
  const tenantName = invoice.tenant?.name || "Viresto";
  const caseText = invoice.case
    ? `${invoice.case.title || "-"}${
        invoice.case.caseNumber ? ` - ${invoice.case.caseNumber}` : ""
      }`
    : copy.noCase;

  return `${copy.whatsappGreeting} ${invoice.client?.name || ""}

${copy.whatsappIntro}

${copy.invoiceNumber}: ${formatInvoiceNumber(invoice.invoiceNumber)}
${copy.status}: ${copy.statuses[invoice.status]}
${copy.caseDetails}: ${caseText}
${copy.issueDate}: ${date(invoice.issueDate, locale)}
${copy.dueDate}: ${date(invoice.dueDate, locale)}
${copy.finalTotal}: ${money(invoice.total, locale)}

${copy.whatsappReview}

${copy.regards}
${tenantName}`.trim();
}

export function buildInvoicePrintHtml(
  invoice: PrintableInvoice,
  requestedLocale?: InvoiceLocale,
) {
  const payments = invoice.payments ?? [];

  const paidPayments = payments.filter((payment) => payment.status === "PAID");

  const paidTotal = paidPayments.reduce(
    (sum, payment) => sum + Number(payment.amount || 0),
    0,
  );

  const remainingTotal = Math.max(0, Number(invoice.total || 0) - paidTotal);

  const locale = detectLocale(requestedLocale);
  const copy = COPY[locale];
  const isRtl = locale === "ar";
  const dir = isRtl ? "rtl" : "ltr";
  const textAlign = isRtl ? "right" : "left";

  const tenant = invoice.tenant;
  const tenantName = tenant?.name || "Viresto";
  const useVirestoLockup =
    !tenant?.logoUrl && tenantName.trim().toLowerCase() === "viresto";
  const tenantEmail = tenant?.email || copy.legalPlatform;
  const invoiceNo = formatInvoiceNumber(invoice.invoiceNumber);
  const caseText = invoice.case
    ? `${invoice.case.title || "-"}${
        invoice.case.caseNumber ? ` - ${invoice.case.caseNumber}` : ""
      }`
    : copy.noCase;

  const rows = invoice.items
    .map((item, index) => {
      const lineTotal =
        item.total ?? Number(item.quantity || 0) * Number(item.unitPrice || 0);

      return `
        <tr>
          <td class="center">${index + 1}</td>
          <td class="description">${escapeHtml(item.description)}</td>
          <td class="center numeric">${escapeHtml(item.quantity)}</td>
          <td class="numeric">${money(item.unitPrice, locale)}</td>
          <td class="numeric strong">${money(lineTotal, locale)}</td>
        </tr>
      `;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="${locale}" dir="${dir}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(copy.invoice)} ${escapeHtml(invoiceNo)}</title>
  <style>
    :root {
      --brand: #0f3d3e;
      --brand-2: #b87333;
      --brand-soft: #f7e9dc;
      --ink: #102d2e;
      --muted: #647c7c;
      --line: #dce9e7;
      --paper: #ffffff;
      --page: #eef5f4;
      --warning: #b45309;
    }

    * { box-sizing: border-box; }

    html {
      min-height: 100%;
      color-scheme: light only;
      background: #eef5f4;
    }

    body { min-height: 100%; }

    body {
      margin: 0;
      padding: 24px;
      background: var(--page);
      color: var(--ink);
      direction: ${dir};
      text-align: ${textAlign};
      font-family: ${
        isRtl
          ? '"Tahoma", "Arial", sans-serif'
          : '"Inter", "Segoe UI", Arial, sans-serif'
      };
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    .paper {
      max-width: 920px;
      min-height: 1120px;
      margin: 0 auto;
      background: var(--paper);
      border: 1px solid var(--line);
      border-radius: 28px;
      overflow: hidden;
      box-shadow: 0 22px 70px rgba(16, 35, 29, 0.14);
    }

    .hero {
      position: relative;
      overflow: hidden;
      display: grid;
      grid-template-columns: minmax(190px, .72fr) minmax(0, 1.28fr);
         grid-template-areas: ${isRtl ? '"brand heading"' : '"heading brand"'};
        gap: 34px;
      padding: 34px 38px;
      color: #fff;
      direction: ltr;
      background:
        radial-gradient(circle at 12% 0%, rgba(255,255,255,.13), transparent 34%),
        linear-gradient(135deg, var(--brand), var(--brand-2));
    }

    .hero::after {
      content: "";
      position: absolute;
      width: 210px;
      height: 210px;
      border-radius: 999px;
      inset-inline-end: -90px;
      bottom: -125px;
      background: rgba(255,255,255,.08);
    }

    .brand {
      position: relative;
      z-index: 1;
      grid-area: brand;
      min-width: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 10px;
      direction: ${dir};
      text-align: center;
    }

    .brand-logo {
      flex: 0 0 auto;
      width: 76px;
      height: 76px;
      border-radius: 22px;
      background: rgba(255,255,255,.13);
      border: 1px solid rgba(255,255,255,.28);
      display: flex;
      align-items: center;
      justify-content: center;
      overflow: hidden;
      box-shadow: inset 0 1px 0 rgba(255,255,255,.18);
    }

    .brand-logo img {
      display: block;
      width: 100%;
      height: 100%;
      object-fit: contain;
      padding: 9px;
      opacity: 1 !important;
      filter: none !important;
    }

    .brand-logo-lockup {
      width: 86px;
      height: 86px;
      border: 1px solid rgba(255,255,255,.28);
      border-radius: 24px;
      background: rgba(255,255,255,.10);
      box-shadow: inset 0 1px 0 rgba(255,255,255,.18);
    }

    .brand-logo-lockup img {
      padding: 8px;
      object-fit: contain;
    }

    .brand-logo-fallback {
      width: 100%;
      height: 100%;
      align-items: center;
      justify-content: center;
      font-size: 32px;
      line-height: 1;
      font-weight: 950;
      letter-spacing: -2px;
    }

    .brand-project-name {
      max-width: 190px;
      color: #fff;
      font-size: 17px;
      line-height: 1.35;
      font-weight: 950;
      overflow-wrap: anywhere;
    }

    .brand-project-subtitle {
      max-width: 190px;
      margin-top: -4px;
      color: rgba(255,255,255,.72);
      font-size: 10.5px;
      line-height: 1.5;
      font-weight: 750;
      overflow-wrap: anywhere;
    }

.invoice-heading {
  position: relative;
  z-index: 1;
  grid-area: heading;
  align-self: center;
  direction: ${dir};
  text-align: ${isRtl ? "right" : "left"};
}

    .invoice-heading .eyebrow {
      color: rgba(255,255,255,.76);
      font-size: 11px;
      font-weight: 800;
      letter-spacing: .08em;
      text-transform: uppercase;
    }

    .invoice-heading h2 {
      margin: 6px 0 0;
      padding-bottom: 3px;
      font-size: 38px;
      line-height: 1.4;
      font-weight: 950;
    }

    .invoice-number {
      display: inline-flex;
      margin-top: 12px;
      padding: 8px 14px;
      border-radius: 999px;
      background: rgba(255,255,255,.14);
      border: 1px solid rgba(255,255,255,.24);
      font-size: 12px;
      font-weight: 900;
      direction: ltr;
      unicode-bidi: isolate;
    }

    .status-chip {
      display: inline-flex;
      margin-top: 0;
      padding: 7px 12px;
      border-radius: 999px;
      color: #fff;
      background: rgba(255,255,255,.12);
      font-size: 11px;
      font-weight: 850;
    }

    .content { padding: 30px 38px 26px; }

    .summary {
      display: grid;
      grid-template-columns: repeat(4, minmax(0, 1fr));
      gap: 12px;
      margin-bottom: 22px;
    }

    .summary-card {
      min-width: 0;
      border: 1px solid var(--line);
      border-radius: 18px;
      padding: 14px;
      background: #fbfdfc;
    }

    .summary-card.total {
      background: var(--brand-soft);
      border-color: #bfd8d4;
    }

    .label {
      color: #456463 !important;
      -webkit-text-fill-color: #456463;
      opacity: 1 !important;
      font-size: 10.5px;
      font-weight: 850;
      margin-bottom: 7px;
    }

    .summary-card.total .label {
      color: #0f3d3e !important;
      -webkit-text-fill-color: #0f3d3e;
    }

    .value {
      font-size: 13.5px;
      font-weight: 950;
      line-height: 1.6;
      overflow-wrap: anywhere;
    }

    .numeric {
      direction: ltr;
      unicode-bidi: isolate;
      white-space: nowrap;
      text-align: ${textAlign};
    }

    .details-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 14px;
      margin-bottom: 22px;
    }

    .box {
      border: 1px solid var(--line);
      direction: ${dir};
      text-align: ${textAlign};
      border-radius: 20px;
      padding: 18px;
      background: #fbfdfc;
      min-height: 132px;
    }

    .box h3 {
      margin: 0 0 12px;
      font-size: 15px;
      font-weight: 950;
      color: var(--brand);
    }

    .box .main-value {
      font-size: 14px;
      font-weight: 950;
      line-height: 1.7;
      overflow-wrap: anywhere;
    }

    .muted {
      margin-top: 4px;
      color: #4d6767 !important;
      -webkit-text-fill-color: #4d6767;
      opacity: 1 !important;
      font-size: 11.5px;
      line-height: 1.8;
      overflow-wrap: anywhere;
    }

    .items-title {
      margin: 0 0 10px;
      font-size: 16px;
      color: var(--brand);
      font-weight: 950;
    }

    .table-wrap {
      overflow: hidden;
      border: 1px solid var(--line);
      border-radius: 18px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      table-layout: fixed;
    }

    th {
      background: var(--brand-soft);
      color: var(--brand);
      font-size: 11.5px;
      padding: 12px 11px;
      text-align: ${textAlign};
      border-bottom: 1px solid var(--line);
      font-weight: 900;
    }

    .status-row {
      margin-top: 12px;
    }

    td {
      padding: 12px 11px;
      font-size: 12px;
      border-bottom: 1px solid #edf4f3;
      vertical-align: top;
    }

    tbody tr:last-child td { border-bottom: none; }
    .center { text-align: center; }
    .strong { font-weight: 950; }
    .description { overflow-wrap: anywhere; }

    .bottom {
      display: grid;
      grid-template-columns: minmax(0, 1fr) 330px;
      gap: 18px;
      margin-top: 20px;
      align-items: stretch;
    }

    .notes {
      border: 1px dashed #bad2cf;
      border-radius: 18px;
      padding: 16px;
      background: #fbfdfc;
      min-height: 148px;
    }

    .notes h3 {
      margin: 0 0 10px;
      color: var(--brand);
      font-size: 14px;
      font-weight: 950;
    }

    .notes p {
      margin: 0;
      color: #3d5a5a !important;
      -webkit-text-fill-color: #3d5a5a;
      font-size: 11.8px;
      line-height: 2;
      white-space: pre-wrap;
      overflow-wrap: anywhere;
    }

    .totals {
      border: 1px solid var(--line);
      border-radius: 20px;
      padding: 15px 16px;
      background: #fbfdfc;
    }

    .total-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 14px;
      padding: 9px 0;
      color: #3d5a5a !important;
      -webkit-text-fill-color: #3d5a5a;
      font-size: 12.5px;
      border-bottom: 1px solid #e7f0ef;
    }

    .total-row:last-child { border-bottom: none; }

    .grand {
      margin-top: 5px;
      padding-top: 15px;
      color: var(--brand);
      font-weight: 950;
      font-size: 18px;
    }

    .payment-strip {
      display: flex;
      justify-content: space-between;
      gap: 16px;
      margin-top: 18px;
      padding: 13px 15px;
      border-radius: 16px;
      background: var(--brand-soft);
      color: var(--brand);
      border: 1px solid #bfd8d4;
      font-size: 11.5px;
      font-weight: 850;
    }

    .signatures {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 34px;
      margin-top: 42px;
    }

    .signature {
      border-top: 1px solid #b6cdca;
      padding-top: 9px;
      color: #587271 !important;
      -webkit-text-fill-color: #587271;
      font-size: 11px;
      text-align: center;
    }

    .footer {
      margin-top: 28px;
      padding-top: 15px;
      border-top: 1px solid #edf4f3;
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 14px;
      color: #587271 !important;
      -webkit-text-fill-color: #587271;
      font-size: 10.5px;
    }

    .closing {
      break-inside: avoid;
      page-break-inside: avoid;
    }

    @media (max-width: 720px) {
      body { padding: 10px; }
      .paper { border-radius: 20px; }
      .hero {
        grid-template-columns: 1fr;
        padding: 26px 24px;
      }
      .invoice-heading { text-align: ${textAlign}; }
      .content { padding: 24px; }
      .summary { grid-template-columns: 1fr 1fr; }
      .details-grid, .bottom { grid-template-columns: 1fr; }
      .footer { flex-direction: column; align-items: flex-start; }
      .hero {
          grid-template-columns: 1fr;
          grid-template-areas:
          "heading"
         "brand";
        }
    }

    @media print {
      body { background: #fff; padding: 0; }
      .paper {
        box-shadow: none;
        border: none;
        border-radius: 0;
        min-height: auto;
      }
      .hero { border-radius: 0; }
      .content { padding: 24px 28px 18px; }
      .hero, .summary, .details-grid, .summary-card, .box, .table-wrap,
      .notes, .totals, .bottom, .payment-strip, .closing {
        break-inside: avoid;
        page-break-inside: avoid;
      }
      thead { display: table-header-group; }
      tr {
        break-inside: avoid;
        page-break-inside: avoid;
      }
      @page { size: A4; margin: 8mm; }
    }
  </style>
</head>
<body>
  <main class="paper">
    <section class="hero">
      <div class="brand">
        ${logoMarkup(invoice, tenantName, useVirestoLockup)}
        <div class="brand-project-name">${escapeHtml(tenantName)}</div>
        <div class="brand-project-subtitle">${escapeHtml(
          tenantEmail || copy.legalPlatform,
        )}</div>
      </div>

      <div class="invoice-heading">
        <div class="eyebrow">Viresto</div>
        <h2>${escapeHtml(copy.invoice)}</h2>
        <div class="invoice-number">${escapeHtml(invoiceNo)}</div>
        <div class="status-row">
          <div class="status-chip">${escapeHtml(copy.statuses[invoice.status])}</div>
        </div>
      </div>
    </section>

    <section class="content">
      <div class="summary">
        <div class="summary-card">
          <div class="label">${escapeHtml(copy.invoiceNumber)}</div>
          <div class="value numeric">${escapeHtml(invoiceNo)}</div>
        </div>
        <div class="summary-card">
          <div class="label">${escapeHtml(copy.issueDate)}</div>
          <div class="value">${escapeHtml(date(invoice.issueDate, locale))}</div>
        </div>
        <div class="summary-card">
          <div class="label">${escapeHtml(copy.dueDate)}</div>
          <div class="value">${escapeHtml(date(invoice.dueDate, locale))}</div>
        </div>
        <div class="summary-card total">
          <div class="label">${escapeHtml(copy.finalTotal)}</div>
          <div class="value numeric">${escapeHtml(money(invoice.total, locale))}</div>
        </div>
      </div>

      <div class="details-grid">
        <div class="box">
          <h3>${escapeHtml(copy.clientDetails)}</h3>
          <div class="main-value">${escapeHtml(invoice.client?.name || "-")}</div>
          <div class="muted numeric">${escapeHtml(invoice.client?.phone || "-")}</div>
          <div class="muted" style="text-align:${textAlign};">${escapeHtml(
            invoice.client?.email || "-",
          )}</div>
        </div>

        <div class="box">
          <h3>${escapeHtml(copy.caseDetails)}</h3>
          <div class="main-value">${escapeHtml(caseText)}</div>
          <div class="muted">
            ${escapeHtml(copy.status)}:
            ${escapeHtml(copy.statuses[invoice.status])}
          </div>
          <div class="muted">
            ${
              payments.length > 0
                ? escapeHtml(`${copy.linkedPayment} (${payments.length})`)
                : escapeHtml(copy.noLinkedPayment)
            }
          </div>
        </div>
      </div>

      <h3 class="items-title">${escapeHtml(copy.items)}</h3>

      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th style="width:50px;text-align:center;">${escapeHtml(copy.number)}</th>
              <th>${escapeHtml(copy.description)}</th>
              <th style="width:82px;text-align:center;">${escapeHtml(copy.quantity)}</th>
              <th style="width:145px;">${escapeHtml(copy.unitPrice)}</th>
              <th style="width:150px;">${escapeHtml(copy.lineTotal)}</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>

      <div class="bottom">
        <div class="notes">
          <h3>${escapeHtml(copy.notes)}</h3>
          <p>${escapeHtml(invoice.notes || copy.noNotes)}</p>
        </div>

        <div class="totals">
          <div class="total-row">
            <span>${escapeHtml(copy.subtotal)}</span>
            <strong class="numeric">${escapeHtml(money(invoice.subtotal, locale))}</strong>
          </div>
          <div class="total-row">
            <span>${escapeHtml(copy.tax)}</span>
            <strong class="numeric">${escapeHtml(money(invoice.tax, locale))}</strong>
          </div>
          <div class="total-row">
            <span>${escapeHtml(copy.discount)}</span>
            <strong class="numeric">${escapeHtml(money(invoice.discount, locale))}</strong>
          </div>
          <div class="total-row grand">
            <span>${escapeHtml(copy.finalTotal)}</span>
            <span class="numeric">${escapeHtml(money(invoice.total, locale))}</span>
          </div>
        </div>
      </div>

${
  payments.length > 0
    ? `
      <div class="payment-strip">
        <span>
          ${escapeHtml(
            locale === "ar"
              ? `عدد الدفعات: ${payments.length}`
              : `Payments: ${payments.length}`,
          )}
        </span>

        <span>
          ${escapeHtml(
            locale === "ar"
              ? `المحصل: ${money(paidTotal, locale)}`
              : `Paid: ${money(paidTotal, locale)}`,
          )}
        </span>

        <span>
          ${escapeHtml(
            locale === "ar"
              ? `المتبقي: ${money(remainingTotal, locale)}`
              : `Remaining: ${money(remainingTotal, locale)}`,
          )}
        </span>
      </div>
    `
    : ""
}

      <div class="closing">
        <div class="signatures">
          <div class="signature">${escapeHtml(copy.officeSignature)}</div>
          <div class="signature">${escapeHtml(copy.clientSignature)}</div>
        </div>

        <div class="footer">
          <span>${escapeHtml(copy.generatedBy)}</span>
          <span class="numeric">${escapeHtml(invoiceNo)}</span>
        </div>
      </div>
    </section>
  </main>

  <script>
    window.addEventListener("load", function () {
      setTimeout(function () {
        window.print();
      }, 250);
    });
  </script>
</body>
</html>`;
}

export function printInvoiceDocument(
  invoice: PrintableInvoice,
  locale?: InvoiceLocale,
) {
  const resolvedLocale = detectLocale(locale);
  const printWindow = window.open("", "_blank", "width=1100,height=850");

  if (!printWindow) {
    toast.error(COPY[resolvedLocale].printPopupBlocked);
    return;
  }

  const printableInvoice: PrintableInvoice = {
    ...invoice,
    tenant: {
      ...invoice.tenant,
      logoUrl: invoice.tenant?.logoUrl
        ? resolveLogoUrl(invoice.tenant.logoUrl)
        : null,
    },
  };

  printWindow.document.open();
  printWindow.document.write(
    buildInvoicePrintHtml(printableInvoice, resolvedLocale),
  );
  printWindow.document.close();
}
