from pathlib import Path

PAGE = Path("src/app/dashboard/reports/page.tsx")
EXPORT = Path("src/lib/export.ts")

if not PAGE.exists():
    raise SystemExit("❌ الملف غير موجود: src/app/dashboard/reports/page.tsx")
if not EXPORT.exists():
    raise SystemExit("❌ الملف غير موجود: src/lib/export.ts")

page = PAGE.read_text(encoding="utf-8")
export = EXPORT.read_text(encoding="utf-8")

# 1) Add stronger export helpers to src/lib/export.ts
if "export function exportSheetsExcel" not in export:
    marker = "export function exportClientFullPDF(client: any) {"
    helpers = """
export function exportSheetsExcel(
  filename: string,
  sheets: { name: string; rows: Record<string, any>[] }[]
) {
  const workbook = XLSX.utils.book_new()

  sheets.forEach((sheet) => {
    const safeName = sheet.name.slice(0, 31) || 'Report'
    const rows = sheet.rows.length ? sheet.rows : [{ ملاحظة: 'لا توجد بيانات' }]
    const worksheet = XLSX.utils.json_to_sheet(rows)

    worksheet['!cols'] = Object.keys(rows[0] || {}).map(() => ({ wch: 22 }))

    XLSX.utils.book_append_sheet(workbook, worksheet, safeName)
  })

  XLSX.writeFile(workbook, `${filename}.xlsx`)
}

export function exportReportPDF(
  filename: string,
  title: string,
  summaryRows: any[][],
  tables: { title: string; columns: string[]; rows: any[][] }[]
) {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'pt',
    format: 'a4',
  })

  doc.addFileToVFS('Amiri-Regular.ttf', amiriFont)
  doc.addFont('Amiri-Regular.ttf', 'Amiri', 'normal')
  doc.setFont('Amiri', 'normal')
  ;(doc as any).setR2L?.(true)

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()

  doc.setTextColor(45, 74, 62)
  doc.setFontSize(20)
  doc.text('Viresto', pageWidth / 2, 38, { align: 'center' })

  doc.setTextColor(0)
  doc.setFontSize(14)
  doc.text(title, pageWidth / 2, 64, { align: 'center' })

  autoTable(doc, {
    startY: 88,
    head: [['القيمة', 'البند']],
    body: summaryRows.map((row) => [row[1] ?? '-', row[0] ?? '-']),
    theme: 'grid',
    styles: {
      font: 'Amiri',
      fontStyle: 'normal',
      halign: 'right',
      fontSize: 10,
      cellPadding: 7,
      minCellHeight: 22,
    },
    headStyles: {
      font: 'Amiri',
      fontStyle: 'normal',
      fillColor: [45, 74, 62],
      textColor: 255,
      halign: 'right',
    },
  })

  let y = ((doc as any).lastAutoTable?.finalY || 110) + 22

  tables.forEach((table) => {
    const body = table.rows.length ? table.rows : [table.columns.map(() => '-')]

    if (y > pageHeight - 120) {
      doc.addPage()
      doc.setFont('Amiri', 'normal')
      y = 45
    }

    doc.setFontSize(13)
    doc.setTextColor(45, 74, 62)
    doc.text(table.title, pageWidth - 40, y, { align: 'right' })

    autoTable(doc, {
      startY: y + 12,
      head: [table.columns],
      body,
      theme: 'grid',
      styles: {
        font: 'Amiri',
        fontStyle: 'normal',
        halign: 'right',
        fontSize: 9,
        cellPadding: 6,
        minCellHeight: 20,
        overflow: 'linebreak',
      },
      headStyles: {
        font: 'Amiri',
        fontStyle: 'normal',
        fillColor: [45, 74, 62],
        textColor: 255,
        halign: 'right',
      },
    })

    y = ((doc as any).lastAutoTable?.finalY || y) + 24
  })

  const pages = (doc as any).internal.getNumberOfPages()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setFont('Amiri', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(120)
    doc.text(
      `Generated by Viresto - ${new Date().toLocaleDateString('ar-JO')} - صفحة ${i} من ${pages}`,
      pageWidth / 2,
      pageHeight - 20,
      { align: 'center' }
    )
  }

  doc.save(`${filename}.pdf`)
}

"""
    if marker not in export:
        raise SystemExit("❌ لم أجد مكان إضافة دوال التصدير داخل src/lib/export.ts")
    export = export.replace(marker, helpers + "\n" + marker)

# 2) Import helpers in reports page
if "exportReportPDF" not in page:
    page = page.replace(
        "import { formatCurrency } from '@/lib/utils'",
        "import { formatCurrency } from '@/lib/utils'\nimport { exportReportPDF, exportSheetsExcel } from '@/lib/export'"
    )

# 3) Add full export functions inside ReportsPage
if "function exportFullExcel()" not in page:
    anchor = """  function exportInvoices() {
    if (!data) return

    const rows = [
      ['رقم الفاتورة', 'الموكل', 'القضية', 'المبلغ', 'الحالة', 'تاريخ الإصدار', 'تاريخ الاستحقاق'],
      ...data.periodInvoices.map((inv) => [
        inv.invoiceNumber || '-',
        inv.client?.name || '-',
        inv.case?.title || '-',
        Number(inv.total || 0),
        invoiceStatus(inv.status),
        formatDate(inv.issueDate),
        formatDate(inv.dueDate),
      ]),
    ]

    downloadCsv(`invoices-report-${year}.csv`, rows)
  }
"""
    addition = anchor + r"""
  function reportTitle() {
    return reportType === 'monthly'
      ? `تقرير ${MONTHS[month]} ${year}`
      : `التقرير السنوي ${year}`
  }

  function reportFilename() {
    return reportType === 'monthly'
      ? `viresto-report-${year}-${String(month + 1).padStart(2, '0')}`
      : `viresto-report-${year}`
  }

  function summaryRows() {
    return [
      ['إيرادات الفترة', formatCurrency(summary.periodRevenue)],
      ['إجمالي التحصيل', formatCurrency(summary.totalPaidAll)],
      ['دفعات معلقة/متأخرة', formatCurrency(summary.pendingPaymentsAmount)],
      ['إجمالي الفواتير', formatCurrency(summary.totalInvoicesAmount)],
      ['فواتير مدفوعة', formatCurrency(summary.paidInvoicesAmount)],
      ['فواتير غير مدفوعة', formatCurrency(summary.unpaidInvoicesAmount)],
      ['فواتير متأخرة', formatCurrency(summary.overdueInvoicesAmount)],
      ['نسبة التحصيل', `${summary.collectionRate}%`],
      ['عدد القضايا', summary.totalCases],
      ['القضايا النشطة', summary.openCases],
      ['القضايا المغلقة/المؤرشفة', summary.closedCases],
      ['المواعيد القادمة', summary.upcomingAppointmentsCount],
      ['المهام المتأخرة', summary.overdueTasksCount],
    ]
  }

  function paymentRowsForExport() {
    return data.periodPayments.map((p) => ({
      القضية: p.case?.title || '-',
      الموكل: p.case?.client?.name || '-',
      المبلغ: Number(p.amount || 0),
      الحالة: paymentStatus(p.status),
      طريقة_الدفع: p.method || '-',
      التاريخ: formatDate(p.paidAt),
      ملاحظات: p.notes || '-',
    }))
  }

  function invoiceRowsForExport() {
    return data.periodInvoices.map((inv) => ({
      رقم_الفاتورة: inv.invoiceNumber || '-',
      الموكل: inv.client?.name || '-',
      القضية: inv.case?.title || '-',
      المبلغ: Number(inv.total || 0),
      الحالة: invoiceStatus(inv.status),
      تاريخ_الإصدار: formatDate(inv.issueDate),
      تاريخ_الاستحقاق: formatDate(inv.dueDate),
    }))
  }

  function appointmentRowsForExport() {
    return data.upcomingAppointments.map((a) => ({
      الموعد: a.title || '-',
      القضية: a.case?.title || '-',
      التاريخ: formatDate(a.startTime),
      المكان: a.location || '-',
    }))
  }

  function taskRowsForExport() {
    return data.overdueTasks.map((t) => ({
      المهمة: t.title || '-',
      القضية: t.case?.title || '-',
      الأولوية: t.priority || '-',
      الاستحقاق: formatDate(t.dueDate),
    }))
  }

  function exportFullExcel() {
    if (!data) return

    exportSheetsExcel(reportFilename(), [
      {
        name: 'الملخص',
        rows: summaryRows().map(([البند, القيمة]) => ({ البند, القيمة })),
      },
      { name: 'الدفعات', rows: paymentRowsForExport() },
      { name: 'الفواتير', rows: invoiceRowsForExport() },
      { name: 'المواعيد القادمة', rows: appointmentRowsForExport() },
      { name: 'المهام المتأخرة', rows: taskRowsForExport() },
      {
        name: 'حالة القضايا',
        rows: caseRows.map(([status, count]) => ({
          الحالة: caseStatusLabel(String(status)),
          العدد: count,
        })),
      },
    ])
  }

  function exportFullPdf() {
    if (!data) return

    exportReportPDF(reportFilename(), reportTitle(), summaryRows(), [
      {
        title: 'دفعات الفترة',
        columns: ['ملاحظات', 'التاريخ', 'طريقة الدفع', 'الحالة', 'المبلغ', 'الموكل', 'القضية'],
        rows: paymentRowsForExport().map((p) => [
          p.ملاحظات,
          p.التاريخ,
          p.طريقة_الدفع,
          p.الحالة,
          formatCurrency(p.المبلغ),
          p.الموكل,
          p.القضية,
        ]),
      },
      {
        title: 'فواتير الفترة',
        columns: ['الاستحقاق', 'الإصدار', 'الحالة', 'المبلغ', 'القضية', 'الموكل', 'رقم الفاتورة'],
        rows: invoiceRowsForExport().map((inv) => [
          inv.تاريخ_الاستحقاق,
          inv.تاريخ_الإصدار,
          inv.الحالة,
          formatCurrency(inv.المبلغ),
          inv.القضية,
          inv.الموكل,
          inv.رقم_الفاتورة,
        ]),
      },
      {
        title: 'المواعيد القادمة',
        columns: ['المكان', 'التاريخ', 'القضية', 'الموعد'],
        rows: appointmentRowsForExport().map((a) => [a.المكان, a.التاريخ, a.القضية, a.الموعد]),
      },
      {
        title: 'المهام المتأخرة',
        columns: ['الاستحقاق', 'الأولوية', 'القضية', 'المهمة'],
        rows: taskRowsForExport().map((t) => [t.الاستحقاق, t.الأولوية, t.القضية, t.المهمة]),
      },
    ])
  }
"""
    if anchor not in page:
        raise SystemExit("❌ لم أجد دالة exportInvoices في صفحة التقارير. ابعث آخر نسخة من src/app/dashboard/reports/page.tsx")
    page = page.replace(anchor, addition)

# 4) Add buttons
if "تصدير Excel شامل" not in page:
    old_buttons = """          <button onClick={() => window.print()} className="btn btn-primary">طباعة</button>
          <button onClick={exportPayments} className="btn btn-secondary">تصدير الدفعات CSV</button>
          <button onClick={exportInvoices} className="btn btn-secondary">تصدير الفواتير CSV</button>"""
    new_buttons = """          <button onClick={() => window.print()} className="btn btn-primary">طباعة</button>
          <button onClick={exportFullPdf} className="btn btn-primary">تصدير PDF شامل</button>
          <button onClick={exportFullExcel} className="btn btn-secondary">تصدير Excel شامل</button>
          <button onClick={exportPayments} className="btn btn-secondary">تصدير الدفعات CSV</button>
          <button onClick={exportInvoices} className="btn btn-secondary">تصدير الفواتير CSV</button>"""
    if old_buttons not in page:
        raise SystemExit("❌ لم أجد أزرار التصدير في صفحة التقارير")
    page = page.replace(old_buttons, new_buttons)

PAGE.write_text(page, encoding="utf-8")
EXPORT.write_text(export, encoding="utf-8")

print("✅ تم تركيب Patch تصدير التقارير PDF/Excel")
print("الآن شغّل:")
print("npm run build")
