"use client";

import type { FormEvent } from "react";
import { useEffect, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { toast } from "sonner";
import PageLoader from "@/components/ui/PageLoader";
import { useLocale } from "@/lib/useLocale";
import type { Locale } from "@/lib/i18n";
import { formatCurrency, formatDate } from "@/lib/utils";
import {
  buildInvoiceWhatsAppMessage,
  formatInvoiceNumber,
  normalizeWhatsAppPhone,
  printInvoiceDocument,
  safeInvoiceFilename,
} from "@/lib/invoice-print";

type InvoiceStatus = "DRAFT" | "UNPAID" | "PAID" | "OVERDUE" | "CANCELLED";

type EditItem = {
  description: string;
  quantity: number;
  unitPrice: number;
};

interface Invoice {
  id: string;
  invoiceNumber: string;
  status: InvoiceStatus;
  issueDate: string;
  dueDate?: string | null;
  subtotal: number;
  tax: number;
  discount: number;
  total: number;
  notes?: string | null;
  client: {
    id: string;
    name: string;
    phone?: string | null;
    whatsapp?: string | null;
    whatsappNumber?: string | null;
    mobile?: string | null;
    email?: string | null;
    archivedAt?: string | null;
  };
  case?: {
    id: string;
    title: string;
    caseNumber?: string | null;
    client?: {
      id?: string;
      name?: string;
      archivedAt?: string | null;
    } | null;
  } | null;
  items: Array<{
    id: string;
    description: string;
    quantity: number;
    unitPrice: number;
    total: number;
  }>;
  payment?: {
    id: string;
    amount: number;
    status: string;
    paidAt?: string | null;
  } | null;
  tenant?: {
    id: string;
    name: string;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    logoUrl?: string | null;
  } | null;
}

const statusLabels: Record<InvoiceStatus, string> = {
  DRAFT: "مسودة",
  UNPAID: "غير مدفوعة",
  PAID: "مدفوعة",
  OVERDUE: "متأخرة",
  CANCELLED: "ملغاة",
};

const statusClasses: Record<InvoiceStatus, string> = {
  DRAFT: "badge badge-gray",
  UNPAID: "badge badge-amber",
  PAID: "badge badge-green",
  OVERDUE: "badge badge-red",
  CANCELLED: "badge badge-gray",
};

const INVOICE_DOCUMENT_COPY = {
  ar: {
    invoice: "فاتورة",
    invoiceNumber: "رقم الفاتورة",
    issueDate: "تاريخ الإصدار",
    dueDate: "تاريخ الاستحقاق",
    finalTotal: "الإجمالي النهائي",
    clientDetails: "بيانات الموكل",
    caseDetails: "بيانات القضية",
    status: "الحالة",
    noCase: "بدون قضية",
    noPayment: "لا توجد دفعة مرتبطة",
    linkedPayment: "مرتبطة بدفعة",
    items: "بنود الفاتورة",
    description: "الوصف",
    quantity: "الكمية",
    unitPrice: "سعر الوحدة",
    total: "الإجمالي",
    subtotal: "المجموع الفرعي",
    tax: "الضريبة",
    discount: "الخصم",
    payment: "الدفعة المرتبطة",
    amount: "المبلغ",
    paymentDate: "تاريخ الدفع",
    notes: "ملاحظات",
    noNotes: "لا توجد ملاحظات إضافية.",
    officeSignature: "توقيع المكتب",
    clientSignature: "توقيع الموكل",
    generatedBy: "تم إنشاء هذه الفاتورة بواسطة Viresto",
    language: "لغة الفاتورة",
    statuses: {
      DRAFT: "مسودة",
      UNPAID: "غير مدفوعة",
      PAID: "مدفوعة",
      OVERDUE: "متأخرة",
      CANCELLED: "ملغاة",
    } as Record<InvoiceStatus, string>,
    paymentStatuses: {
      PAID: "مدفوعة",
      PENDING: "معلّقة",
      OVERDUE: "متأخرة",
      CANCELLED: "ملغاة",
    } as Record<string, string>,
  },
  en: {
    invoice: "Invoice",
    invoiceNumber: "Invoice number",
    issueDate: "Issue date",
    dueDate: "Due date",
    finalTotal: "Final total",
    clientDetails: "Client details",
    caseDetails: "Case details",
    status: "Status",
    noCase: "No case",
    noPayment: "No linked payment",
    linkedPayment: "Linked to a payment",
    items: "Invoice items",
    description: "Description",
    quantity: "Quantity",
    unitPrice: "Unit price",
    total: "Total",
    subtotal: "Subtotal",
    tax: "Tax",
    discount: "Discount",
    payment: "Linked payment",
    amount: "Amount",
    paymentDate: "Payment date",
    notes: "Notes",
    noNotes: "No additional notes.",
    officeSignature: "Office signature",
    clientSignature: "Client signature",
    generatedBy: "This invoice was generated by Viresto",
    language: "Invoice language",
    statuses: {
      DRAFT: "Draft",
      UNPAID: "Unpaid",
      PAID: "Paid",
      OVERDUE: "Overdue",
      CANCELLED: "Cancelled",
    } as Record<InvoiceStatus, string>,
    paymentStatuses: {
      PAID: "Paid",
      PENDING: "Pending",
      OVERDUE: "Overdue",
      CANCELLED: "Cancelled",
    } as Record<string, string>,
  },
};

const VIRESTO_BRAND_LOGO_PATH = "/viresto-logo.png";

const VIRESTO_FALLBACK_LOGO =
  "data:image/svg+xml;charset=UTF-8," +
  encodeURIComponent(`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
      <rect width="512" height="512" rx="128" fill="#ffffff"/>
      <path
        d="M116 128h82l58 166 58-166h82L294 384h-76L116 128Z"
        fill="#12382d"
      />
    </svg>
  `);

function formatInvoiceDate(value: string | null | undefined, locale: Locale) {
  if (!value) return "-";

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return "-";

  return new Intl.DateTimeFormat(locale === "ar" ? "ar-JO" : "en-US", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(parsed);
}

function formatInvoiceMoney(value: number, locale: Locale) {
  return new Intl.NumberFormat(locale === "ar" ? "ar-JO" : "en-US", {
    style: "currency",
    currency: "JOD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Number(value || 0));
}

function extractClientPhone(data: unknown) {
  const payload = data as any;
  const candidates = [
    payload?.whatsappNumber,
    payload?.whatsapp,
    payload?.phone,
    payload?.mobile,
    payload?.client?.whatsappNumber,
    payload?.client?.whatsapp,
    payload?.client?.phone,
    payload?.client?.mobile,
    payload?.data?.whatsappNumber,
    payload?.data?.whatsapp,
    payload?.data?.phone,
    payload?.data?.mobile,
    payload?.data?.client?.whatsappNumber,
    payload?.data?.client?.whatsapp,
    payload?.data?.client?.phone,
    payload?.data?.client?.mobile,
    payload?.data?.data?.whatsappNumber,
    payload?.data?.data?.whatsapp,
    payload?.data?.data?.phone,
    payload?.data?.data?.mobile,
  ];

  return (
    candidates.find(
      (value) => typeof value === "string" && value.trim().length > 0,
    ) || null
  );
}

function toDateInput(value?: string | null) {
  if (!value) return "";
  return new Date(value).toISOString().slice(0, 10);
}

function roundMoney(value: number) {
  return Math.round((value + Number.EPSILON) * 100) / 100;
}

function paymentStatusLabel(status?: string | null) {
  const map: Record<string, string> = {
    PAID: "مدفوعة",
    PENDING: "معلّقة",
    OVERDUE: "متأخرة",
    CANCELLED: "ملغاة",
  };

  return status ? (map[status] ?? status) : "-";
}

function isArchivedInvoice(invoice: Invoice) {
  return Boolean(
    invoice.client?.archivedAt || invoice.case?.client?.archivedAt,
  );
}

function money(value: number) {
  if (!Number.isFinite(value) || value === 0) {
    return "0 د.أ";
  }

  return formatCurrency(value);
}

export default function InvoiceDetailsPage() {
  const params = useParams();
  const router = useRouter();
  const localeState = useLocale() as { locale?: Locale };
  const appLocale: Locale = localeState?.locale === "en" ? "en" : "ar";
  const id = params.id as string;

  const [invoice, setInvoice] = useState<Invoice | null>(null);
  const [loading, setLoading] = useState(true);
  const [pdfLoading, setPdfLoading] = useState(false);
  const [editOpen, setEditOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [mounted, setMounted] = useState(false);
  const [invoiceLocale, setInvoiceLocale] = useState<Locale>(appLocale);

  const [editDueDate, setEditDueDate] = useState("");
  const [editTax, setEditTax] = useState(0);
  const [editDiscount, setEditDiscount] = useState(0);
  const [editNotes, setEditNotes] = useState("");
  const [editItems, setEditItems] = useState<EditItem[]>([]);

  const invoiceRef = useRef<HTMLDivElement | null>(null);
  function confirmToast(message: string) {
    return new Promise<boolean>((resolve) => {
      let settled = false;

      const toastId = toast(message, {
        duration: 10000,
        action: {
          label: "تأكيد",
          onClick: () => {
            if (settled) return;
            settled = true;
            toast.dismiss(toastId);
            resolve(true);
          },
        },
        onDismiss: () => {
          if (settled) return;
          settled = true;
          resolve(false);
        },
        onAutoClose: () => {
          if (settled) return;
          settled = true;
          resolve(false);
        },
      });
    });
  }

  async function load() {
    if (!id || id === "undefined" || id === "null") {
      setInvoice(null);
      setLoading(false);
      return;
    }

    try {
      setLoading(true);

      const res = await fetch(`/api/invoices/${id}`, {
        cache: "no-store",
      });

      if (res.status === 401) {
        window.location.href = "/login";
        return;
      }

      const data = await res.json().catch(() => ({}));

      if (!res.ok) {
        console.error("Invoice load failed:", {
          id,
          status: res.status,
          data,
        });

        setInvoice(null);
        return;
      }

      setInvoice(data.data?.invoice ?? data.data ?? data.invoice ?? null);
    } catch (error) {
      console.error("Invoice load error:", error);
      setInvoice(null);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    setInvoiceLocale(appLocale);
  }, [appLocale]);

  useEffect(() => {
    if (id) load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  function openEditModal() {
    if (!invoice) return;

    if (invoice.status === "PAID") {
      toast.error(
        "لا يمكن تعديل البيانات المالية لفاتورة مدفوعة. غيّر الحالة أولًا إذا احتجت تعديلها.",
      );
      return;
    }

    setEditDueDate(toDateInput(invoice.dueDate));
    setEditTax(invoice.tax || 0);
    setEditDiscount(invoice.discount || 0);
    setEditNotes(invoice.notes || "");
    setEditItems(
      invoice.items.map((item) => ({
        description: item.description,
        quantity: item.quantity,
        unitPrice: item.unitPrice,
      })),
    );
    setEditOpen(true);
  }

  function updateEditItem(index: number, key: keyof EditItem, value: string) {
    setEditItems((prev) =>
      prev.map((item, i) =>
        i === index
          ? {
              ...item,
              [key]: key === "description" ? value : Number(value || 0),
            }
          : item,
      ),
    );
  }

  function addEditItem() {
    setEditItems((prev) => [
      ...prev,
      {
        description: "",
        quantity: 1,
        unitPrice: 0,
      },
    ]);
  }

  function removeEditItem(index: number) {
    setEditItems((prev) => prev.filter((_, i) => i !== index));
  }

  const editSubtotal = roundMoney(
    editItems.reduce((sum, item) => {
      const quantity = Number(item.quantity || 0);
      const unitPrice = Number(item.unitPrice || 0);
      return sum + quantity * unitPrice;
    }, 0),
  );

  const editTotal = roundMoney(
    editSubtotal + Number(editTax || 0) - Number(editDiscount || 0),
  );

  async function submitEdit(e: FormEvent) {
    e.preventDefault();
    if (!invoice) return;

    const cleanItems = editItems
      .map((item) => ({
        description: item.description.trim(),
        quantity: Number(item.quantity || 0),
        unitPrice: Number(item.unitPrice || 0),
      }))
      .filter((item) => item.description);

    if (cleanItems.length === 0) {
      toast.error("أضف بند واحد على الأقل");
      return;
    }

    if (cleanItems.some((item) => item.quantity <= 0 || item.unitPrice < 0)) {
      toast.error("تأكد أن الكمية أكبر من صفر وأن سعر الوحدة غير سالب");
      return;
    }

    if (Number(editTax || 0) < 0 || Number(editDiscount || 0) < 0) {
      toast.error("الضريبة والخصم لا يمكن أن تكون قيمهم سالبة");
      return;
    }

    if (editTotal < 0) {
      toast.error("الخصم لا يمكن أن يكون أكبر من المجموع والضريبة");
      return;
    }

    try {
      setSaving(true);

      const res = await fetch(`/api/invoices/${invoice.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          dueDate: editDueDate || null,
          tax: Number(editTax || 0),
          discount: Number(editDiscount || 0),
          notes: editNotes,
          items: cleanItems,
        }),
      });

      const data = await res.json().catch(() => ({}));

      if (!res.ok) {
        toast.error(data.message || data.error || "تعذر تعديل الفاتورة");
        return;
      }

      toast.success("تم تعديل الفاتورة");
      setEditOpen(false);
      await load();
    } finally {
      setSaving(false);
    }
  }

  async function updateStatus(nextStatus: InvoiceStatus) {
    if (!invoice || invoice.status === nextStatus) return;

    if (nextStatus === "PAID" && !invoice.case) {
      toast.error(
        "لا يمكن تعليم الفاتورة كمدفوعة لأنها غير مرتبطة بقضية. اربطها بقضية أولًا حتى يتم إنشاء دفعة صحيحة.",
      );
      return;
    }

    if (invoice.payment && invoice.status === "PAID" && nextStatus !== "PAID") {
      const confirmed = await confirmToast(
        "هذه الفاتورة مدفوعة ومرتبطة بدفعة. تغيير الحالة سيحدّث حالة الدفعة المرتبطة حسب الحالة الجديدة. هل تريد المتابعة؟",
      );

      if (!confirmed) return;
    }

    const res = await fetch(`/api/invoices/${invoice.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: nextStatus }),
    });

    const data = await res.json().catch(() => ({}));

    if (!res.ok) {
      toast.error(data.message || data.error || "تعذر تحديث حالة الفاتورة");
      return;
    }

    toast.success("تم تحديث حالة الفاتورة");
    await load();
  }

  async function deleteInvoice() {
    if (!invoice) return;

    if (isArchivedInvoice(invoice)) {
      toast.error("لا يمكن حذف فاتورة مرتبطة بموكل مؤرشف");
      return;
    }

    if (invoice.payment) {
      toast.error(
        "لا يمكن حذف هذه الفاتورة لأنها مرتبطة بدفعة. عالج الدفعة المرتبطة أولًا ثم حاول مرة أخرى.",
      );
      return;
    }

    const confirmed = await confirmToast("هل أنت متأكد من حذف هذه الفاتورة؟");
    if (!confirmed) return;

    const res = await fetch(`/api/invoices/${invoice.id}`, {
      method: "DELETE",
    });

    const data = await res.json().catch(() => ({}));

    if (!res.ok) {
      toast.error(data.message || data.error || "تعذر حذف الفاتورة");
      return;
    }

    toast.success("تم حذف الفاتورة");
    router.push("/dashboard/invoices");
  }

  async function sendInvoiceWhatsApp() {
    if (!invoice) return;

    let rawPhone =
      invoice.client?.whatsappNumber ||
      invoice.client?.whatsapp ||
      invoice.client?.phone ||
      invoice.client?.mobile ||
      null;

    if (!rawPhone && invoice.client?.id) {
      try {
        const response = await fetch(`/api/clients/${invoice.client.id}`, {
          cache: "no-store",
        });
        const data = response.ok ? await response.json().catch(() => ({})) : {};

        rawPhone = extractClientPhone(data);
      } catch {
        rawPhone = null;
      }
    }

    const phone = normalizeWhatsAppPhone(rawPhone);

    if (!phone) {
      toast.error(
        invoiceLocale === "ar"
          ? "لا يوجد رقم واتساب أو هاتف محفوظ لهذا الموكل"
          : "No WhatsApp or phone number is saved for this client",
      );
      return;
    }

    window.open(
      `https://wa.me/${phone}?text=${encodeURIComponent(
        buildInvoiceWhatsAppMessage(invoice, invoiceLocale),
      )}`,
      "_blank",
      "noopener,noreferrer",
    );
  }

  async function downloadInvoicePDF() {
    if (!invoiceRef.current || !invoice) return;

    try {
      setPdfLoading(true);

      const html2canvas = (await import("html2canvas")).default;
      const { jsPDF } = await import("jspdf");

      const canvas = await html2canvas(invoiceRef.current, {
        scale: 2,
        useCORS: true,
        backgroundColor: "#ffffff",
      });

      const imgData = canvas.toDataURL("image/png");

      const pdf = new jsPDF({
        orientation: "p",
        unit: "mm",
        format: "a4",
      });

      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 10;
      const usableWidth = pageWidth - margin * 2;
      const imgWidth = usableWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      let heightLeft = imgHeight;
      let position = margin;

      pdf.addImage(imgData, "PNG", margin, position, imgWidth, imgHeight);
      heightLeft -= pageHeight - margin * 2;

      while (heightLeft > 0) {
        position = heightLeft - imgHeight + margin;
        pdf.addPage();
        pdf.addImage(imgData, "PNG", margin, position, imgWidth, imgHeight);
        heightLeft -= pageHeight - margin * 2;
      }

      pdf.save(`${safeInvoiceFilename(invoice.invoiceNumber)}.pdf`);
    } catch (error) {
      console.error(error);
      toast.error("تعذر إنشاء ملف PDF");
    } finally {
      setPdfLoading(false);
    }
  }

  function printInvoice() {
    if (!invoice) return;
    printInvoiceDocument(invoice, invoiceLocale);
  }

  if (!mounted || loading) {
    return <PageLoader />;
  }

  if (!invoice) {
    return (
      <div className="space-y-5 stagger">
        <div
          className="relative overflow-hidden rounded-[28px] border p-6"
          style={{
            background:
              "linear-gradient(135deg, var(--sidebar) 0%, var(--sidebar-hover) 60%, var(--sidebar-dark) 100%)",
            borderColor: "rgba(255,255,255,0.12)",
            boxShadow: "0 18px 50px rgba(45, 74, 62, 0.18)",
          }}
        >
          <h1 className="text-2xl font-black text-white">
            الفاتورة غير موجودة
          </h1>

          <p className="mt-2 max-w-2xl text-sm font-semibold leading-7 text-white/75">
            تعذر العثور على الفاتورة المطلوبة، أو أنها حُذفت، أو أن الرابط غير
            صحيح.
          </p>
        </div>

        <div className="card p-8 text-center">
          <button
            onClick={() => router.push("/dashboard/invoices")}
            className="btn btn-primary"
          >
            رجوع للفواتير
          </button>
        </div>
      </div>
    );
  }

  const tenantName = invoice.tenant?.name || "Viresto";
  const useVirestoLockup =
    !invoice.tenant?.logoUrl && tenantName.trim().toLowerCase() === "viresto";
  const archivedInvoice = isArchivedInvoice(invoice);
  const canEditFinancials = invoice.status !== "PAID";
  const invoiceCopy = INVOICE_DOCUMENT_COPY[invoiceLocale];
  const invoiceIsRtl = invoiceLocale === "ar";

  return (
    <div className="space-y-5 stagger print:space-y-4 print:bg-white print:text-black">
      {/* Hero */}
      <div
        className="relative overflow-hidden rounded-[28px] border p-6 print:hidden"
        style={{
          background:
            "linear-gradient(135deg, var(--sidebar) 0%, var(--sidebar-hover) 60%, var(--sidebar-dark) 100%)",
          borderColor: "rgba(255,255,255,0.12)",
          boxShadow: "0 18px 50px rgba(45, 74, 62, 0.18)",
        }}
      >
        <div
          className="absolute -left-14 -top-14 h-40 w-40 rounded-full"
          style={{ background: "rgba(245, 200, 66, 0.16)" }}
        />

        <div
          className="absolute -bottom-20 right-16 h-52 w-52 rounded-full"
          style={{ background: "rgba(255,255,255,0.08)" }}
        />

        <div className="relative z-10 flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between">
          <div>
            <button
              onClick={() => router.push("/dashboard/invoices")}
              className="mb-3 rounded-full px-3 py-1 text-xs font-black text-white/80 transition hover:bg-white/10"
            >
              ← رجوع للفواتير
            </button>

            <div
              className="mb-3 inline-flex rounded-full px-3 py-1 text-xs font-black"
              style={{
                background: "rgba(255,255,255,0.14)",
                color: "#fff",
                border: "1px solid rgba(255,255,255,0.18)",
              }}
            >
              تفاصيل الفاتورة
            </div>

            <h1 className="text-2xl font-black text-white">
              فاتورة {formatInvoiceNumber(invoice.invoiceNumber)}
            </h1>

            <p className="mt-2 max-w-3xl text-sm font-semibold leading-7 text-white/75">
              عرض بيانات الفاتورة، البنود، الموكل، القضية، الدفعة المرتبطة،
              وإجراءات الطباعة والإرسال.
            </p>

            <div className="mt-4 flex flex-wrap gap-2">
              <span
                className="rounded-full px-3 py-1 text-xs font-black"
                style={{
                  background: "rgba(255,255,255,0.14)",
                  color: "#fff",
                }}
              >
                الحالة: {statusLabels[invoice.status]}
              </span>

              <span
                className="rounded-full px-3 py-1 text-xs font-black"
                style={{
                  background: "rgba(245,200,66,0.18)",
                  color: "#fff",
                }}
              >
                الإجمالي: {money(invoice.total)}
              </span>

              {archivedInvoice && (
                <span
                  className="rounded-full px-3 py-1 text-xs font-black"
                  style={{
                    background: "#fff7ed",
                    color: "#b45309",
                    border: "1px solid rgba(180, 83, 9, 0.18)",
                  }}
                >
                  موكل مؤرشف
                </span>
              )}
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <div
              className="inline-flex rounded-2xl border p-1"
              style={{
                background: "rgba(255,255,255,0.12)",
                borderColor: "rgba(255,255,255,0.22)",
              }}
              aria-label={invoiceCopy.language}
            >
              <button
                type="button"
                onClick={() => setInvoiceLocale("ar")}
                className="rounded-xl px-3 py-2 text-xs font-black transition"
                style={{
                  background: invoiceLocale === "ar" ? "#fff" : "transparent",
                  color:
                    invoiceLocale === "ar"
                      ? "var(--sidebar)"
                      : "rgba(255,255,255,0.82)",
                }}
              >
                العربية
              </button>

              <button
                type="button"
                onClick={() => setInvoiceLocale("en")}
                className="rounded-xl px-3 py-2 text-xs font-black transition"
                style={{
                  background: invoiceLocale === "en" ? "#fff" : "transparent",
                  color:
                    invoiceLocale === "en"
                      ? "var(--sidebar)"
                      : "rgba(255,255,255,0.82)",
                }}
              >
                English
              </button>
            </div>

            <button
              onClick={openEditModal}
              disabled={invoice.status === "PAID"}
              title={
                invoice.status === "PAID"
                  ? "لا يمكن تعديل البيانات المالية لفاتورة مدفوعة"
                  : "تعديل الفاتورة"
              }
              className="btn disabled:cursor-not-allowed disabled:opacity-60"
              style={{
                background: "#fff",
                color: "var(--sidebar)",
                borderColor: "rgba(255,255,255,0.32)",
              }}
            >
              تعديل
            </button>

            <button
              onClick={printInvoice}
              className="btn"
              style={{
                background: "rgba(255,255,255,0.14)",
                color: "#fff",
                borderColor: "rgba(255,255,255,0.22)",
              }}
            >
              طباعة
            </button>

            <button
              onClick={downloadInvoicePDF}
              disabled={pdfLoading}
              className="btn"
              style={{
                background: "rgba(255,255,255,0.14)",
                color: "#fff",
                borderColor: "rgba(255,255,255,0.22)",
              }}
            >
              {pdfLoading ? "جاري إنشاء PDF..." : "PDF"}
            </button>

            <button
              onClick={sendInvoiceWhatsApp}
              className="btn"
              style={{
                background: "rgba(34,197,94,0.18)",
                color: "#fff",
                borderColor: "rgba(34,197,94,0.32)",
              }}
            >
              واتساب
            </button>

            <button
              onClick={deleteInvoice}
              disabled={archivedInvoice || !!invoice.payment}
              title={
                archivedInvoice
                  ? "لا يمكن حذف فاتورة مرتبطة بموكل مؤرشف"
                  : invoice.payment
                    ? "لا يمكن حذف فاتورة مرتبطة بدفعة"
                    : "حذف الفاتورة"
              }
              className="btn disabled:cursor-not-allowed disabled:opacity-60"
              style={{
                background: "rgba(239,68,68,0.18)",
                color: "#fff",
                borderColor: "rgba(239,68,68,0.32)",
              }}
            >
              حذف
            </button>
          </div>
        </div>
      </div>

      {/* Stats */}
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 print:hidden">
        <InfoCard
          label="إجمالي الفاتورة"
          value={money(invoice.total)}
          hint="المبلغ النهائي"
          tone="green"
        />

        <InfoCard
          label="المجموع الفرعي"
          value={money(invoice.subtotal)}
          hint="قبل الضريبة والخصم"
        />

        <InfoCard
          label="الضريبة"
          value={money(invoice.tax)}
          hint="قيمة الضريبة"
          tone="amber"
        />

        <InfoCard
          label="الخصم"
          value={money(invoice.discount)}
          hint="إجمالي الخصم"
          tone="red"
        />
      </div>

      <div className="grid grid-cols-1 gap-5 xl:grid-cols-12 print:block">
        {/* Sidebar */}
        <div className="space-y-5 xl:col-span-4 print:hidden">
          <div className="card p-5">
            <div className="mb-4 flex items-center justify-between gap-3">
              <div>
                <h2 className="font-black" style={{ color: "var(--text)" }}>
                  حالة الفاتورة
                </h2>

                <p className="mt-1 text-xs" style={{ color: "var(--text-3)" }}>
                  غيّر حالة الفاتورة حسب التحصيل
                </p>
              </div>

              <span className={statusClasses[invoice.status]}>
                {statusLabels[invoice.status]}
              </span>
            </div>

            <select
              value={invoice.status}
              onChange={(e) => updateStatus(e.target.value as InvoiceStatus)}
              className="input"
              aria-label="تغيير حالة الفاتورة"
            >
              <option value="DRAFT">مسودة</option>
              <option value="UNPAID">غير مدفوعة</option>
              <option value="PAID">مدفوعة</option>
              <option value="OVERDUE">متأخرة</option>
              <option value="CANCELLED">ملغاة</option>
            </select>

            {invoice.payment && (
              <div
                className="mt-4 rounded-2xl border p-4 text-sm font-bold"
                style={{
                  borderColor: "var(--border)",
                  background: "var(--green-soft)",
                  color: "var(--sidebar)",
                }}
              >
                هذه الفاتورة مرتبطة بدفعة.
              </div>
            )}

            {archivedInvoice && (
              <div
                className="mt-4 rounded-2xl border p-4 text-sm font-bold"
                style={{
                  borderColor: "rgba(180, 83, 9, 0.22)",
                  background: "#fff7ed",
                  color: "#b45309",
                }}
              >
                هذه الفاتورة مرتبطة بموكل مؤرشف. يمكن تعديل بيانات الفاتورة
                وتحديث حالتها، لكن لا يمكن حذفها لحماية السجل المالي.
              </div>
            )}
          </div>

          <div className="card p-5">
            <h2 className="font-black" style={{ color: "var(--text)" }}>
              بيانات الموكل
            </h2>

            <div className="mt-4 space-y-3">
              <MiniLine label="الاسم" value={invoice.client?.name} />
              <MiniLine label="الهاتف" value={invoice.client?.phone} />
              <MiniLine label="البريد" value={invoice.client?.email} />

              {archivedInvoice && (
                <div
                  className="rounded-2xl border p-3 text-xs font-black"
                  style={{
                    background: "#fff7ed",
                    color: "#b45309",
                    borderColor: "rgba(180, 83, 9, 0.18)",
                  }}
                >
                  موكل مؤرشف
                </div>
              )}
            </div>
          </div>

          <div className="card p-5">
            <h2 className="font-black" style={{ color: "var(--text)" }}>
              بيانات القضية
            </h2>

            <div className="mt-4 space-y-3">
              <MiniLine
                label="القضية"
                value={invoice.case?.title || "بدون قضية"}
              />
              <MiniLine label="رقم القضية" value={invoice.case?.caseNumber} />
            </div>
          </div>

          <div className="card p-5">
            <h2 className="font-black" style={{ color: "var(--text)" }}>
              التواريخ
            </h2>

            <div className="mt-4 space-y-3">
              <MiniLine
                label="تاريخ الإصدار"
                value={formatDate(invoice.issueDate)}
              />
              <MiniLine
                label="تاريخ الاستحقاق"
                value={invoice.dueDate ? formatDate(invoice.dueDate) : "-"}
              />
            </div>
          </div>
        </div>

        {/* Invoice Printable Area */}
        <div className="space-y-5 xl:col-span-8 print:block">
          <div
            ref={invoiceRef}
            dir={invoiceIsRtl ? "rtl" : "ltr"}
            className="overflow-hidden rounded-[30px] border bg-white text-start text-slate-950 shadow-sm print:rounded-none print:border-0 print:shadow-none"
            style={{ borderColor: "#dbe7e1" }}
          >
            {/* Branded Header */}
            <div
              className="relative overflow-hidden px-7 py-7 text-white sm:px-9"
              style={{
                background:
                  "radial-gradient(circle at 12% 0%, rgba(255,255,255,0.14), transparent 34%), linear-gradient(135deg, #12382d, #215846)",
              }}
            >
              <div
                className="absolute -bottom-24 end-[-72px] h-52 w-52 rounded-full"
                style={{ background: "rgba(255,255,255,0.08)" }}
              />

              <div
                dir="ltr"
                className={`relative z-10 flex flex-col gap-6 sm:items-center sm:justify-between ${
                  invoiceIsRtl ? "sm:flex-row" : "sm:flex-row-reverse"
                }`}
              >
                <div className="flex shrink-0 flex-col items-center justify-center gap-2 text-center">
                  {useVirestoLockup ? (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={VIRESTO_BRAND_LOGO_PATH}
                      alt="Viresto"
                      className="h-[86px] w-[86px] rounded-[24px] border border-white/25 bg-white/10 object-contain p-2"
                      onError={(event) => {
                        event.currentTarget.onerror = null;
                        event.currentTarget.src = VIRESTO_FALLBACK_LOGO;
                      }}
                    />
                  ) : (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={invoice.tenant?.logoUrl || "/icon.png"}
                      alt={tenantName}
                      className="h-[86px] w-[86px] rounded-[24px] border border-white/25 bg-white object-contain p-2"
                      onError={(event) => {
                        event.currentTarget.onerror = null;
                        event.currentTarget.src = VIRESTO_FALLBACK_LOGO;
                      }}
                    />
                  )}

                  <p
                    dir={invoiceIsRtl ? "rtl" : "ltr"}
                    className="max-w-[190px] break-words text-center text-base font-black text-white"
                  >
                    {tenantName}
                  </p>

                  <p
                    dir={invoiceIsRtl ? "rtl" : "ltr"}
                    className="max-w-[190px] break-words text-center text-[10px] font-bold text-white/65"
                  >
                    {invoice.tenant?.email || "Legal Platform"}
                  </p>
                </div>

                <div
                  dir={invoiceIsRtl ? "rtl" : "ltr"}
                  className={`min-w-0 ${
                    invoiceIsRtl ? "text-right" : "text-left"
                  }`}
                >
                  <p className="text-xs font-black uppercase tracking-[0.16em] text-white/60">
                    Viresto
                  </p>

                  <h2 className="mt-1 text-4xl font-black">
                    {invoiceCopy.invoice}
                  </h2>

                  <span
                    dir="ltr"
                    className="mt-3 inline-flex rounded-full border border-white/25 bg-white/10 px-4 py-2 text-xs font-black"
                  >
                    {formatInvoiceNumber(invoice.invoiceNumber)}
                  </span>

                  <p className="mt-3 text-xs font-black text-white/80">
                    {invoiceCopy.status}: {invoiceCopy.statuses[invoice.status]}
                  </p>
                </div>
              </div>
            </div>

            <div className="p-6 sm:p-8">
              {/* Summary */}
              <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">
                {[
                  {
                    label: invoiceCopy.invoiceNumber,
                    value: formatInvoiceNumber(invoice.invoiceNumber),
                    ltr: true,
                  },
                  {
                    label: invoiceCopy.issueDate,
                    value: formatInvoiceDate(invoice.issueDate, invoiceLocale),
                  },
                  {
                    label: invoiceCopy.dueDate,
                    value: formatInvoiceDate(invoice.dueDate, invoiceLocale),
                  },
                  {
                    label: invoiceCopy.finalTotal,
                    value: formatInvoiceMoney(invoice.total, invoiceLocale),
                    total: true,
                    ltr: true,
                  },
                ].map((item) => (
                  <div
                    key={item.label}
                    dir={invoiceIsRtl ? "rtl" : "ltr"}
                    className={`rounded-2xl border p-4 ${
                      invoiceIsRtl ? "text-right" : "text-left"
                    }`}
                    style={{
                      borderColor: item.total ? "#c7ded3" : "#dbe7e1",
                      background: item.total ? "#eaf4ef" : "#fbfdfc",
                    }}
                  >
                    <p
                      className="text-[11px] font-black"
                      style={{
                        color: item.total ? "#12382d" : "#385248",
                        WebkitTextFillColor: item.total ? "#12382d" : "#385248",
                        opacity: 1,
                      }}
                    >
                      {item.label}
                    </p>
                    <p
                      dir={item.ltr ? "ltr" : undefined}
                      className="mt-2 break-words text-sm font-black"
                      style={{
                        color: item.total ? "#12382d" : "#10231d",
                        textAlign: invoiceIsRtl ? "right" : "left",
                      }}
                    >
                      {item.value}
                    </p>
                  </div>
                ))}
              </div>

              {/* Client and case */}
              <div className="mb-6 grid gap-4 md:grid-cols-2">
                <div
                  dir={invoiceIsRtl ? "rtl" : "ltr"}
                  className={`rounded-3xl border p-5 ${
                    invoiceIsRtl ? "text-right" : "text-left"
                  }`}
                  style={{
                    borderColor: "#dbe7e1",
                    background: "#fbfdfc",
                  }}
                >
                  <h3 className="text-base font-black text-[#12382d]">
                    {invoiceCopy.clientDetails}
                  </h3>
                  <p className="mt-3 text-base font-black">
                    {invoice.client?.name || "-"}
                  </p>
                  <p
                    dir="ltr"
                    className="mt-1 text-xs font-semibold text-[#40584f]"
                    style={{
                      textAlign: invoiceIsRtl ? "right" : "left",
                    }}
                  >
                    {invoice.client?.phone || "-"}
                  </p>
                  <p
                    className="mt-1 break-all text-xs font-semibold text-[#40584f]"
                    style={{
                      textAlign: invoiceIsRtl ? "right" : "left",
                    }}
                  >
                    {invoice.client?.email || "-"}
                  </p>
                </div>

                <div
                  dir={invoiceIsRtl ? "rtl" : "ltr"}
                  className={`rounded-3xl border p-5 ${
                    invoiceIsRtl ? "text-right" : "text-left"
                  }`}
                  style={{
                    borderColor: "#dbe7e1",
                    background: "#fbfdfc",
                  }}
                >
                  <h3 className="text-base font-black text-[#12382d]">
                    {invoiceCopy.caseDetails}
                  </h3>
                  <p className="mt-3 text-base font-black">
                    {invoice.case?.title || invoiceCopy.noCase}
                  </p>
                  <p className="mt-1 text-xs font-semibold text-[#40584f]">
                    {invoice.case?.caseNumber || "-"}
                  </p>
                  <p className="mt-1 text-xs font-semibold text-[#40584f]">
                    {invoice.payment
                      ? invoiceCopy.linkedPayment
                      : invoiceCopy.noPayment}
                  </p>
                </div>
              </div>

              {/* Items */}
              <h3 className="mb-3 text-lg font-black text-[#12382d]">
                {invoiceCopy.items}
              </h3>

              <div
                className="overflow-hidden rounded-3xl border"
                style={{ borderColor: "#dbe7e1" }}
              >
                <div className="overflow-x-auto">
                  <table className="w-full border-collapse">
                    <thead style={{ background: "#eaf4ef" }}>
                      <tr>
                        <th className="w-14 px-4 py-3 text-center text-xs font-black text-[#12382d]">
                          #
                        </th>
                        <th className="px-4 py-3 text-start text-xs font-black text-[#12382d]">
                          {invoiceCopy.description}
                        </th>
                        <th className="w-24 px-4 py-3 text-center text-xs font-black text-[#12382d]">
                          {invoiceCopy.quantity}
                        </th>
                        <th className="w-40 px-4 py-3 text-start text-xs font-black text-[#12382d]">
                          {invoiceCopy.unitPrice}
                        </th>
                        <th className="w-40 px-4 py-3 text-start text-xs font-black text-[#12382d]">
                          {invoiceCopy.total}
                        </th>
                      </tr>
                    </thead>

                    <tbody>
                      {invoice.items.map((item, index) => (
                        <tr
                          key={item.id}
                          className="border-t"
                          style={{ borderColor: "#edf2ef" }}
                        >
                          <td className="px-4 py-3 text-center text-xs font-bold">
                            {index + 1}
                          </td>
                          <td className="px-4 py-3 text-sm font-bold">
                            {item.description}
                          </td>
                          <td
                            dir="ltr"
                            className="px-4 py-3 text-center text-xs font-bold"
                          >
                            {item.quantity}
                          </td>
                          <td
                            dir="ltr"
                            className="px-4 py-3 text-start text-xs font-bold"
                          >
                            {formatInvoiceMoney(item.unitPrice, invoiceLocale)}
                          </td>
                          <td
                            dir="ltr"
                            className="px-4 py-3 text-start text-xs font-black"
                          >
                            {formatInvoiceMoney(item.total, invoiceLocale)}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* Notes and totals */}
              <div className="mt-6 grid gap-4 md:grid-cols-[minmax(0,1fr)_340px]">
                <div
                  className="min-h-40 rounded-3xl border border-dashed p-5"
                  style={{
                    borderColor: "#c8d8d0",
                    background: "#fbfdfc",
                  }}
                >
                  <h3 className="text-base font-black text-[#12382d]">
                    {invoiceCopy.notes}
                  </h3>
                  <p className="mt-3 whitespace-pre-wrap text-sm leading-8 text-[#314a40]">
                    {invoice.notes || invoiceCopy.noNotes}
                  </p>
                </div>

                <div
                  className="rounded-3xl border p-5"
                  style={{
                    borderColor: "#dbe7e1",
                    background: "#fbfdfc",
                  }}
                >
                  {[
                    {
                      label: invoiceCopy.subtotal,
                      value: invoice.subtotal,
                    },
                    { label: invoiceCopy.tax, value: invoice.tax },
                    {
                      label: invoiceCopy.discount,
                      value: invoice.discount,
                    },
                  ].map((line) => (
                    <div
                      key={line.label}
                      className="flex items-center justify-between gap-4 border-b py-3 text-sm"
                      style={{ borderColor: "#e8f0ec" }}
                    >
                      <span className="font-semibold text-[#314a40]">
                        {line.label}
                      </span>
                      <strong dir="ltr">
                        {formatInvoiceMoney(line.value, invoiceLocale)}
                      </strong>
                    </div>
                  ))}

                  <div className="flex items-center justify-between gap-4 pt-5 text-lg font-black text-[#12382d]">
                    <span>{invoiceCopy.finalTotal}</span>
                    <span dir="ltr">
                      {formatInvoiceMoney(invoice.total, invoiceLocale)}
                    </span>
                  </div>
                </div>
              </div>

              {invoice.payment && (
                <div
                  className="mt-5 rounded-2xl border px-5 py-4"
                  style={{
                    borderColor: "#c7ded3",
                    background: "#eaf4ef",
                  }}
                >
                  <div className="grid gap-3 text-sm md:grid-cols-3">
                    <div>
                      <p className="text-xs font-bold text-[#40584f]">
                        {invoiceCopy.amount}
                      </p>
                      <p dir="ltr" className="mt-1 font-black">
                        {formatInvoiceMoney(
                          invoice.payment.amount,
                          invoiceLocale,
                        )}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs font-bold text-[#40584f]">
                        {invoiceCopy.status}
                      </p>
                      <p className="mt-1 font-black">
                        {invoiceCopy.paymentStatuses[invoice.payment.status] ||
                          invoice.payment.status}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs font-bold text-[#40584f]">
                        {invoiceCopy.paymentDate}
                      </p>
                      <p className="mt-1 font-black">
                        {formatInvoiceDate(
                          invoice.payment.paidAt,
                          invoiceLocale,
                        )}
                      </p>
                    </div>
                  </div>
                </div>
              )}

              <div className="mt-12 grid grid-cols-2 gap-10">
                <div className="border-t pt-3 text-center text-xs font-semibold text-[#40584f]">
                  {invoiceCopy.officeSignature}
                </div>
                <div className="border-t pt-3 text-center text-xs font-semibold text-[#40584f]">
                  {invoiceCopy.clientSignature}
                </div>
              </div>

              <div
                className="mt-8 flex flex-col gap-3 border-t pt-4 text-[11px] text-[#40584f] sm:flex-row sm:items-center sm:justify-between"
                style={{ borderColor: "#edf2ef" }}
              >
                <span>{invoiceCopy.generatedBy}</span>
                <span dir="ltr">
                  {formatInvoiceNumber(invoice.invoiceNumber)}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Edit Modal */}
      {editOpen && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4 print:hidden"
          onClick={() => setEditOpen(false)}
        >
          <form
            onSubmit={submitEdit}
            onClick={(e) => e.stopPropagation()}
            className="card max-h-[90vh] w-full max-w-4xl overflow-y-auto p-6"
          >
            <div className="mb-5 flex items-center justify-between gap-4">
              <div>
                <h2
                  className="text-xl font-black"
                  style={{ color: "var(--text)" }}
                >
                  تعديل الفاتورة
                </h2>

                <p className="mt-1 text-sm" style={{ color: "var(--text-3)" }}>
                  تعديل التواريخ والبنود والضريبة والخصم. لا يمكن تعديل فاتورة
                  مدفوعة.
                </p>
              </div>

              <button
                type="button"
                onClick={() => setEditOpen(false)}
                className="rounded-xl px-3 py-2 text-sm font-bold hover:bg-black/5"
              >
                ✕
              </button>
            </div>

            {!canEditFinancials && (
              <div
                className="mb-4 rounded-2xl border p-4 text-sm font-bold"
                style={{
                  borderColor: "#fbbf24",
                  background: "var(--amber-soft)",
                  color: "#92400e",
                }}
              >
                هذه الفاتورة مدفوعة، لذلك تم منع تعديل البيانات المالية لحماية
                السجلات.
              </div>
            )}

            <div className="grid gap-4 md:grid-cols-3">
              <label className="space-y-2">
                <span className="text-sm font-bold">تاريخ الاستحقاق</span>
                <input
                  type="date"
                  value={editDueDate}
                  onChange={(e) => setEditDueDate(e.target.value)}
                  className="input"
                  disabled={!canEditFinancials}
                />
              </label>

              <label className="space-y-2">
                <span className="text-sm font-bold">الضريبة</span>
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  value={editTax}
                  onChange={(e) => setEditTax(Number(e.target.value || 0))}
                  className="input"
                  disabled={!canEditFinancials}
                />
              </label>

              <label className="space-y-2">
                <span className="text-sm font-bold">الخصم</span>
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  value={editDiscount}
                  onChange={(e) => setEditDiscount(Number(e.target.value || 0))}
                  className="input"
                  disabled={!canEditFinancials}
                />
              </label>
            </div>

            <div className="mt-5">
              <div className="mb-3 flex items-center justify-between gap-3">
                <h3 className="font-black" style={{ color: "var(--text)" }}>
                  البنود
                </h3>

                <button
                  type="button"
                  onClick={addEditItem}
                  className="btn btn-ghost"
                  disabled={!canEditFinancials}
                >
                  + إضافة بند
                </button>
              </div>

              <div className="space-y-3">
                {editItems.map((item, index) => (
                  <div
                    key={index}
                    className="grid gap-3 rounded-2xl border p-3 md:grid-cols-[1fr_120px_140px_90px]"
                    style={{ borderColor: "var(--border)" }}
                  >
                    <input
                      value={item.description}
                      onChange={(e) =>
                        updateEditItem(index, "description", e.target.value)
                      }
                      placeholder="وصف البند"
                      className="input"
                      disabled={!canEditFinancials}
                    />

                    <input
                      type="number"
                      min="0.01"
                      step="0.01"
                      value={item.quantity}
                      onChange={(e) =>
                        updateEditItem(index, "quantity", e.target.value)
                      }
                      placeholder="الكمية"
                      className="input"
                      disabled={!canEditFinancials}
                    />

                    <input
                      type="number"
                      min="0"
                      step="0.01"
                      value={item.unitPrice}
                      onChange={(e) =>
                        updateEditItem(index, "unitPrice", e.target.value)
                      }
                      placeholder="سعر الوحدة"
                      className="input"
                      disabled={!canEditFinancials}
                    />

                    <button
                      type="button"
                      onClick={() => removeEditItem(index)}
                      className="rounded-xl px-3 py-2 text-sm font-bold text-red-600 hover:bg-red-50 disabled:opacity-40"
                      disabled={!canEditFinancials || editItems.length === 1}
                    >
                      حذف
                    </button>
                  </div>
                ))}
              </div>
            </div>

            <label className="mt-5 block space-y-2">
              <span className="text-sm font-bold">ملاحظات</span>

              <textarea
                value={editNotes}
                onChange={(e) => setEditNotes(e.target.value)}
                rows={4}
                className="input min-h-28"
                disabled={!canEditFinancials}
              />
            </label>

            <div className="mt-5 flex justify-end">
              <div
                className="w-full max-w-sm space-y-2 rounded-2xl border p-4"
                style={{ borderColor: "var(--border)" }}
              >
                <MoneyLine label="المجموع الفرعي" value={editSubtotal} />
                <MoneyLine label="الضريبة" value={Number(editTax || 0)} />
                <MoneyLine label="الخصم" value={Number(editDiscount || 0)} />

                <div className="flex justify-between border-t pt-2 text-lg font-black">
                  <span>الإجمالي</span>
                  <span>{money(editTotal)}</span>
                </div>
              </div>
            </div>

            <div className="mt-6 flex justify-end gap-2">
              <button
                type="button"
                onClick={() => setEditOpen(false)}
                className="btn btn-ghost"
              >
                إلغاء
              </button>

              <button
                type="submit"
                disabled={saving || !canEditFinancials}
                className="btn btn-primary"
              >
                {saving ? "جارٍ الحفظ..." : "حفظ التعديلات"}
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
}

function InfoCard({
  label,
  value,
  hint,
  tone,
}: {
  label: string;
  value: string | number;
  hint: string;
  tone?: "green" | "amber" | "red";
}) {
  const style =
    tone === "green"
      ? {
          background: "var(--green-soft)",
          color: "var(--sidebar)",
        }
      : tone === "amber"
        ? {
            background: "var(--amber-soft)",
            color: "#92400e",
          }
        : tone === "red"
          ? {
              background: "var(--red-soft)",
              color: "#dc2626",
            }
          : {
              background: "var(--card)",
              color: "var(--text)",
            };

  return (
    <div
      className="card p-5"
      style={{
        background: style.background,
        borderColor: "var(--border)",
      }}
    >
      <p className="text-xs font-black" style={{ color: style.color }}>
        {label}
      </p>

      <p className="mt-2 text-2xl font-black" style={{ color: style.color }}>
        {value}
      </p>

      <p className="mt-1 text-xs font-bold" style={{ color: "var(--text-3)" }}>
        {hint}
      </p>
    </div>
  );
}

function MiniLine({ label, value }: { label: string; value?: string | null }) {
  return (
    <div
      className="rounded-2xl border p-3"
      style={{
        borderColor: "var(--border)",
        background: "var(--card)",
      }}
    >
      <p className="text-xs font-black" style={{ color: "var(--text-3)" }}>
        {label}
      </p>

      <p
        className="mt-1 break-words text-sm font-bold"
        style={{ color: value ? "var(--text)" : "var(--text-3)" }}
      >
        {value || "غير محدد"}
      </p>
    </div>
  );
}

function MoneyLine({ label, value }: { label: string; value: number }) {
  return (
    <div className="flex justify-between text-sm">
      <span>{label}</span>
      <strong>{money(value)}</strong>
    </div>
  );
}
